spring:
  autoconfigure:
    exclude:
      # Profil jdbc używa DataSource (połączenie z bazą), ale nie używa JPA/Hibernate
      # Wyłączamy tylko JPA, zostawiamy DataSource
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  datasource:
    # DB_URL to zmienna środowiskowa z connection stringiem do Neon Tech
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
