services:
  - type: web
    name: pojazdy-carrent
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: APP_PROFILE
        value: json
        jwt:
          secret: ${JWT_SECRET:ThisIsAVeryLongSecretKeyForJWTSigningAtLeast256BitsLong!!}
          expiration-ms: 86400000